name: yell-backend-dev
on:
  push:
    branches:
      - dev
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true
    
    # Configure Docker with Credentials
    - name: Configure Docker
      run: |
        gcloud auth configure-docker
      
    # Build the Docker image
    - name: Build & Publish
      env:
        YELL_SIG_KEY: ${{ secrets.YELL_HS256_KEY }}
        YELL_ENC_KEY: ${{ secrets.YELL_A256GCM_KEY }}
        YELL_DB_USER: ${{ secrets.YELL_DB_USER }}
        YELL_DB_PASS: ${{ secrets.YELL_DB_PASS }}
        YELL_DB_HOST: ${{ secrets.YELL_DB_HOST }}
        YELL_DB_NAME: ${{ secrets.YELL_DB_NAME }}
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT }}
        echo "$YELL_SIG_KEY" > sig
        echo "$YELL_ENC_KEY" > enc
        echo "$YELL_DB_USER" > db_user
        echo "$YELL_DB_PASS" > db_pass
        echo "$YELL_DB_HOST" > db_host
        echo "$YELL_DB_NAME" > db_name
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION_DEV }}
        gcloud config set run/region us-central1
      
    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |
        gcloud run deploy ${{ secrets.GCP_APPLICATION_DEV }} --image gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION_DEV }} \
        --platform managed \
        --allow-unauthenticated \
        --memory 256M \
        --vpc-connector sql-connector