name: yell-backend-dev
on:
  push:
    branches:
      - dev
jobs:
  setup-build-publish-deploy:
    name: Checkout, Login and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    # Write env
    - name: Prepare Environment
      env:
        YELL_SIG_KEY: ${{ secrets.YELL_HS256_KEY }}
        YELL_ENC_KEY: ${{ secrets.YELL_A256GCM_KEY }}
        YELL_DB_USER: ${{ secrets.YELL_DB_USER }}
        YELL_DB_PASS: ${{ secrets.YELL_DB_PASS }}
        YELL_DB_HOST: ${{ secrets.YELL_DB_HOST }}
        YELL_DB_NAME: ${{ secrets.YELL_DB_NAME }}
        YELL_MAIL_USERNAME: ${{ secrets.YELL_MAIL_USERNAME }}
        YELL_MAIL_PASSWORD: ${{ secrets.YELL_MAIL_PASSWORD }}
        YELL_MAIN_URL_DEV: ${{ secrets.YELL_MAIN_URL_DEV }}
      run: |
        echo "$YELL_SIG_KEY" > sig
        echo "$YELL_ENC_KEY" > enc
        echo "$YELL_DB_USER" > db_user
        echo "$YELL_DB_PASS" > db_pass
        echo "$YELL_DB_HOST" > db_host
        echo "$YELL_DB_NAME" > db_name
        echo "$YELL_MAIL_USERNAME" > mail_username
        echo "$YELL_MAIL_PASSWORD" > mail_password
        echo "$YELL_MAIN_URL_DEV" > main_url

    # Login
    - name: Heroku Login
      run: |
        cat > ~/.netrc <<EOF
          machine api.heroku.com
            login $HEROKU_EMAIL
            password $HEROKU_API_KEY
          machine git.heroku.com
            login $HEROKU_EMAIL
            password $HEROKU_API_KEY
        EOF
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}

    # Add remote
    - name: Add Heroku Remote
      run: heroku git:remote --app $HEROKU_APP_NAME
      env:
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME_DEV }}

    # Push to Heroku
    - name: Push to Heroku
      run: git push heroku main